<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">


<!-- Steering Link -->
<link name="steering_link">

</link>

<joint name="steering_joint" type="revolute">
  <parent link="base_footprint"/>
  <child link="steering_link"/>
  <origin xyz="${wheel_xoff} 0 0.05" rpy="-${pi/2} 0 0"/>
  <axis xyz="0 1 0"/>
  <limit effort="10.0" velocity="1.0" lower="-0.7854" upper="0.7854"/>
</joint>


<!-- Front Left Wheel -->
<link name="front_left_wheel_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
    <material name="Gray">
      <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
  </visual>

  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
  </collision>

  <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
</link>

<joint name="front_left_wheel_joint" type="revolute">
  <parent link="base_footprint"/>
  <child link="front_left_wheel_link"/>
  <origin xyz="${wheel_xoff}  ${(base_width/2 + wheel_ygap)} 0.05" rpy="-${pi/2} 0 0"/>
  <axis xyz="0 1 0"/>
  <limit effort="10.0" velocity="1.0" lower="-0.7854" upper="0.7854"/>
</joint>

<!-- Front Right Wheel -->
<link name="front_right_wheel_link">
  <!-- Same as front_left_wheel_link -->
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
    <material name="Gray">
      <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
  </visual>

  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
  </collision>

  <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
</link>

<joint name="front_right_wheel_joint" type="revolute">
  <parent link="base_footprint"/>
  <child link="front_right_wheel_link"/>
  <origin xyz="${wheel_xoff} ${-(base_width/2 + wheel_ygap)} 0.05" rpy="-${pi/2} 0 0"/>
  <axis xyz="0 1 0"/>
  <limit effort="10.0" velocity="1.0" lower="-0.7854" upper="0.7854"/>
</joint>


<!-- Rear Wheels Link -->
  <link name="rear_wheels_link">
    <!-- Inertial properties -->
    <inertial>
      <mass value="1.0"/> <!-- Adjust mass as needed -->
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>

    <!-- Visual elements -->
    <visual>
      <!-- Left Wheel Visual -->
      <origin xyz="0 ${(base_width/2 + wheel_ygap)} 0" rpy="-${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
      <!-- Right Wheel Visual -->
    <visual>
      <origin xyz="0 ${-(base_width/2 + wheel_ygap)} 0" rpy="-${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>

    <!-- Collision elements -->
    <collision>
      <!-- Left Wheel Collision -->
      <origin xyz="0 ${(base_width/2 + wheel_ygap)} 0" rpy="-${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>

      <!-- Right Wheel Collision -->
      <origin xyz="0 ${-(base_width/2 + wheel_ygap)} 0" rpy="-${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <!-- Traction Joint -->
  <joint name="traction_joint" type="continuous">
    <parent link="base_footprint"/>
    <child link="rear_wheels_link"/>
    <origin xyz="${-wheel_xoff} 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 1 0"/> <!-- Adjust axis if necessary -->
  </joint>

</robot>
<!-- Rear Left Wheel -->
<!--<link name="rear_left_wheel_link">
  Same as front_left_wheel_link
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
    <material name="Gray">
      <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
  </visual>

  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
  </collision>

  <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
</link>

<joint name="rear_left_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="rear_left_wheel_link"/>
  <origin xyz="0 ${(base_width/2 + wheel_ygap)} 0" rpy="-${pi/2} 0 0"/>
  <axis xyz="0 0 1"/>
</joint>

Rear Right Wheel
<link name="rear_left_wheel_link">
Same as front_left_wheel_link 
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
    <material name="Gray">
      <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
  </visual>

  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
    </geometry>
  </collision>

  <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
</link>

<joint name="traction_joint" type="continuous">
  <parent link="base_link"/>
  <child link="rear_right_wheel_link"/>
  <origin xyz="0 ${-(base_width/2 + wheel_ygap)} 0" rpy="-${pi/2} 0 0"/>
  <axis xyz="0 0 1"/>
</joint>-->